version: '3'
volumes:
    psql:
services:
    psql:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - psql:/var/lib/postgresql/data
        ports:
            - 5432:5432
